In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("Bank_Personal_Loan_Modelling.csv")
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB

In [5]:
df.describe()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.338400,20.104600,73.774200,93152.503000,2.396400,1.937938,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.467954,46.033729,2121.852197,1.147663,1.747659,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,-3.000000,8.000000,9307.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,93437.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,94608.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,96651.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

In [6]:
df.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [7]:
df.dtypes

ID                      int64
Age                     int64
Experience              int64
Income                  int64
ZIP Code                int64
Family                  int64
CCAvg                 float64
Education               int64
Mortgage                int64
Personal Loan           int64
Securities Account      int64
CD Account              int64
Online                  int64
CreditCard              int64
dtype: object

In [8]:
df.shape

(5000, 14)

In [9]:
df.mean()

ID                     2500.500000
Age                      45.338400
Experience               20.104600
Income                   73.774200
ZIP Code              93152.503000
Family                    2.396400
CCAvg                     1.937938
Education                 1.881000
Mortgage                 56.498800
Personal Loan             0.096000
Securities Account        0.104400
CD Account                0.060400
Online                    0.596800
CreditCard                0.294000
dtype: float64

In [10]:
df.columns

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Personal Loan', 'Securities Account',
       'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [11]:
X = df.drop(['Personal Loan'],axis=1)
y =df['Personal Loan']
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    0
4997    0
4998    0
4999    0
Name: Personal Loan, Length: 5000, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train,y_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [14]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear',random_state = 0)
classifier.fit(X_train,y_train)

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

SVC(kernel='linear', random_state=0)

In [15]:
y_pred =classifier.predict(X_test)
y_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.956

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98      1368
           1       0.86      0.60      0.71       132

    accuracy                           0.96      1500
   macro avg       0.91      0.79      0.84      1500
weighted avg       0.95      0.96      0.95      1500

In [18]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[1355   13]
 [  53   79]]

In [19]:
from sklearn.tree import DecisionTreeClassifier
classifierdtc = DecisionTreeClassifier(criterion='entropy',random_state = 0)
classifierdtc.fit(X_train,y_train)

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [20]:
y_preddtc = classifierdtc.predict(X_test)
y_preddtc

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_preddtc)

0.976

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_preddtc))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1368
           1       0.84      0.89      0.87       132

    accuracy                           0.98      1500
   macro avg       0.92      0.94      0.93      1500
weighted avg       0.98      0.98      0.98      1500

In [23]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_preddtc)

array([[1346,   22],
       [  14,  118]], dtype=int64)

In [24]:
from sklearn.linear_model import LogisticRegression
classifierlr = LogisticRegression(random_state = 0,penalty = 'l2',C = 1.2)
classifierlr.fit(X_train,y_train)

LogisticRegression(C=1.2, random_state=0)

In [25]:
y_predlr = classifierlr.predict(X_test)
y_predlr

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predlr)

0.9533333333333334

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predlr))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1368
           1       0.82      0.61      0.70       132

    accuracy                           0.95      1500
   macro avg       0.89      0.80      0.84      1500
weighted avg       0.95      0.95      0.95      1500

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_predlr)

array([[1350,   18],
       [  52,   80]], dtype=int64)

In [29]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [30]:
pred = knn.predict(X_test)

In [31]:
from sklearn.neighbors import KNeighborsClassifier
classifierknn = KNeighborsClassifier(n_neighbors=20,metric = 'minkowski',p = 2)
classifierknn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=20)

In [32]:
y_predknn = classifierknn.predict(X_test)
y_predknn

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predknn)

0.9413333333333334

In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predknn))

              precision    recall  f1-score   support

           0       0.94      0.99      0.97      1368
           1       0.87      0.39      0.54       132

    accuracy                           0.94      1500
   macro avg       0.91      0.69      0.76      1500
weighted avg       0.94      0.94      0.93      1500

In [35]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_predknn))

[[1360    8]
 [  80   52]]

In [36]:
from sklearn.ensemble import RandomForestClassifier
classifierrfc = RandomForestClassifier(n_estimators =100 , criterion ='entropy', random_state = 0)
classifierrfc.fit(X_train, y_train)

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

RandomForestClassifier(criterion='entropy', random_state=0)

In [37]:
y_predrfc = classifierrfc.predict(X_test)
y_predrfc

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predrfc)

0.9833333333333333

In [39]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predrfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1368
           1       0.92      0.89      0.90       132

    accuracy                           0.98      1500
   macro avg       0.96      0.94      0.95      1500
weighted avg       0.98      0.98      0.98      1500

In [40]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_predrfc)

array([[1358,   10],
       [  15,  117]], dtype=int64)

In [41]:
from sklearn.naive_bayes import GaussianNB
classifiernb = GaussianNB()
classifiernb.fit(X_train,y_train)

GaussianNB()

In [42]:
y_prednb = classifiernb.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_prednb)

0.8993333333333333

In [44]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_prednb))

              precision    recall  f1-score   support

           0       0.96      0.93      0.94      1368
           1       0.45      0.60      0.51       132

    accuracy                           0.90      1500
   macro avg       0.70      0.76      0.73      1500
weighted avg       0.91      0.90      0.91      1500

In [45]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_prednb)

array([[1270,   98],
       [  53,   79]], dtype=int64)

In [46]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifierrfc,X_train,y_train,cv = 5)
scores,scores.mean

(array([0.98714286, 0.98571429, 0.97285714, 0.98285714, 0.98428571]),
 <function ndarray.mean>)