In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv("water_potability.csv")
dataset.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 256.1 KB

In [5]:
dataset.isnull().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [6]:
dataset.shape

(3276, 10)

In [7]:
dataset.describe()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
count,2785.000000,3276.000000,3276.000000,3276.000000,2495.000000,3276.000000,3276.000000,3114.000000,3276.000000,3276.000000
mean,7.080795,196.369496,22014.092526,7.122277,333.775777,426.205111,14.284970,66.396293,3.966786,0.390110
std,1.594320,32.879761,8768.570828,1.583085,41.416840,80.824064,3.308162,16.175008,0.780382,0.487849
min,0.000000,47.432000,320.942611,0.352000,129.000000,181.483754,2.200000,0.738000,1.450000,0.000000
25%,6.093092,176.850538,15666.690297,6.127421,307.699498,365.734414,12.065801,55.844536,3.439711,0.000000
50%,7.036752,196.967627,20927.833607,7.130299,333.073546,421.884968,14.218338,66.622485,3.955028,0.000000
75%,8.062066,216.667456,27332.762127,8.114887,359.950170,481.792304,16.557652,77.337473,4.500320,1.000000
max,14.000000,323.124000,61227.196008,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000,1.000000

In [8]:
drop = dataset.isnull().sum()/dataset.shape[0]*100
miss = drop[drop>20].keys()

In [9]:
drop

ph                 14.987790
Hardness            0.000000
Solids              0.000000
Chloramines         0.000000
Sulfate            23.840049
Conductivity        0.000000
Organic_carbon      0.000000
Trihalomethanes     4.945055
Turbidity           0.000000
Potability          0.000000
dtype: float64

In [10]:
dataset1 = dataset.drop(miss,axis=1)
dataset1.shape

(3276, 9)

In [11]:
dataset1.isnull().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [12]:
num_cols = dataset1.select_dtypes(["int64","float64"]).keys()
num_cols

Index(['ph', 'Hardness', 'Solids', 'Chloramines', 'Conductivity',
       'Organic_carbon', 'Trihalomethanes', 'Turbidity', 'Potability'],
      dtype='object')

In [13]:
for i in num_cols:
    dataset1[i].fillna(dataset1[i].mean(),inplace = True)

In [14]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               3276 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Conductivity     3276 non-null   float64
 5   Organic_carbon   3276 non-null   float64
 6   Trihalomethanes  3276 non-null   float64
 7   Turbidity        3276 non-null   float64
 8   Potability       3276 non-null   int64
dtypes: float64(8), int64(1)
memory usage: 230.5 KB

In [15]:
X = dataset1.drop('Potability',axis=1)
X
y=dataset1['Potability']
y

0       0
1       0
2       0
3       0
4       0
       ..
3271    1
3272    1
3273    1
3274    1
3275    1
Name: Potability, Length: 3276, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [17]:
X_train.shape, X_test.shape, y_train.shape,y_test.shape

((2620, 8), (656, 8), (2620,), (656,))

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier1 = RandomForestClassifier(n_estimators =10 , criterion ='entropy', random_state = 40)
classifier1.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=40)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train,y_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [20]:
y_pred = classifier1.predict(X_test)

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       421
           1       0.36      1.00      0.53       235

    accuracy                           0.36       656
   macro avg       0.18      0.50      0.26       656
weighted avg       0.13      0.36      0.19       656

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.35823170731707316

In [23]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[  0, 421],
       [  0, 235]], dtype=int64)

In [24]:
from sklearn.svm import SVC
classifier2 = SVC(kernel='linear', probability=False, random_state=40)
classifier2.fit(X_train,y_train)

SVC(kernel='linear', random_state=40)

In [26]:
y_pred2 = classifier2.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred2,y_test)

0.6417682926829268

In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.64      1.00      0.78       421
           1       0.00      0.00      0.00       235

    accuracy                           0.64       656
   macro avg       0.32      0.50      0.39       656
weighted avg       0.41      0.64      0.50       656

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred2)

array([[421,   0],
       [235,   0]], dtype=int64)

In [30]:
from sklearn.tree import DecisionTreeClassifier
classifier3 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0) 
classifier3.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [38]:
y_pred3 = classifier3.predict(X_test)

In [39]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred3)

0.5746951219512195

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.67      0.66      0.67       421
           1       0.41      0.43      0.42       235

    accuracy                           0.57       656
   macro avg       0.54      0.54      0.54       656
weighted avg       0.58      0.57      0.58       656

In [41]:
from sklearn.linear_model import LogisticRegression
classifier4 = LogisticRegression(penalty='l2', random_state = 0)
classifier4.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [42]:
y_pred4 = classifier4.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred4)

0.6417682926829268

In [44]:
from sklearn.metrics import classification_report
print(classification_report(y_pred4,y_test))

              precision    recall  f1-score   support

           0       1.00      0.64      0.78       656
           1       0.00      0.00      0.00         0

    accuracy                           0.64       656
   macro avg       0.50      0.32      0.39       656
weighted avg       1.00      0.64      0.78       656

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [45]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred4,y_test)

array([[421, 235],
       [  0,   0]], dtype=int64)